### ISSUE TITLE
JacksonRequest.parseNetworkResponse: An error occurred while parsing network response

### ISSUE THREAD

**Issue by hamedgol** [jinxul/Baboon#1]
When i parse response , display like this error :

`JacksonRequest.parseNetworkResponse: An error occurred while parsing network response:
                                                             com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
                                                              at [Source: buffer(com.android.okhttp.internal.http.HttpConnection$UnknownLengthSource@2777340).inputStream(); line: 1, column: 2]
                                                                 at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
                                                                 at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
                                                                 at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456)
                                                                 at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2689)
                                                                 at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:878)
                                                                 at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772)
                                                                 at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3825)
                                                                 at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3774)
                                                                 at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2913)
                                                                 at com.spothero.volley.JacksonRequest.parseNetworkResponse(JacksonRequest.java:185)
                                                                 at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:116)`

and this error

`FATAL EXCEPTION: main
                                                                     Process: com.givekesh.baboon, PID: 12525
                                                                     java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                         at com.givekesh.baboon.Utils.FeedProvider$1.onResponse(FeedProvider.java:68)
                                                                         at com.givekesh.baboon.Utils.FeedProvider$1.onResponse(FeedProvider.java:57)
                                                                         at com.spothero.volley.JacksonRequest.deliverError(JacksonRequest.java:173)
                                                                         at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

How is solved it?

**Comment by jinxul** [comment]
most likely there's something wrong with your JSON file or JSON mapper. could you provide those?

**Comment by hamedgol** [comment]
Which version do you use in plugin?
I use last version , and display same error.
please attach your compatible plugin's version .

This is my json : 
http://androidesign.ir/wp-json/wp/v2/posts

**Comment by jinxul** [comment]
if you mean json plugin for WP then its the same as yours (but with some customisation - [CHECK HERE](https://github.com/jinxul/Custom-REST-API))

as i said before most likely your problem is json mapper. you didn't provide any so im guessing you're using my [mapper](https://github.com/jinxul/Baboon/blob/master/app/src/main/java/com/givekesh/baboon/Utils/Posts/POJOS/Posts.java) which only map few keys, so when you trying to pars your json file with my mapper, JACKSON will produce a fatal exception since it cant map your json file(with all those extra keys)

either use filter/custom route at your back-end to match my mapper or write an appropriate json mapper capable of mapping your json file.
